const STABLE_TOOL_ERROR_ENTRIES = [
  ["local_image_request_invalid", "本地图片传输请求无效，请使用项目相对路径和稳定图片 ID。"],
  ["local_image_source_invalid", "无法导入源图片：请确认它是项目内可安全读取的 PNG、JPEG 或 WebP，且不超过 64 MiB 和 1 亿像素。"],
  ["local_image_import_failed", "无法发布本地图片，请检查 artifact 仓库后再继续。"],
  ["local_image_destination_exists", "导出目标已存在，未覆盖文件；请指定新的目标文件名。"],
  ["local_image_export_failed", "无法导出图片：请检查图片 ID、项目相对路径、格式扩展名及目录权限；目标不能位于 artifact 仓库内。"],
  ["local_image_transfer_failed", "本地图片传输失败，请检查运行时状态；不要切换生成入口。"],
  ["annotation_image_mismatch", "标注与父图片不匹配。"],
  ["annotation_not_found", "未找到指定标注。"],
  ["annotation_save_failed", "保存图片标注失败。"],
  ["api_provider_not_configured", "API Key 图片 Provider 尚未配置。"],
  ["artifact_not_found", "未找到指定图片产物。"],
  ["artifact_ignore_write_failed", "无法安全保护图片产物目录。"],
  ["artifact_read_failed", "读取图片产物失败。"],
  ["artifact_reveal_failed", "无法在文件夹中显示图片。"],
  ["editor_session_not_found", "画布会话不存在或已经释放。"],
  ["editor_state_invalid", "画布状态无效。"],
  ["editor_state_unavailable", "画布状态暂时不可用。"],
  ["edit_submission_in_flight", "当前画布提交正在执行，暂时不能签发新修订。"],
  ["edit_submission_limit", "当前图片的画布提交记录已达到上限。"],
  ["edit_submission_mismatch", "画布提交与当前父图片、标注或完整编辑请求不匹配。"],
  ["edit_submission_state_invalid", "画布提交状态无效。"],
  ["edit_submission_state_unavailable", "画布提交状态暂时不可用。"],
  ["host_observation_state_invalid", "宿主观察状态无效。"],
  ["host_observation_unavailable", "宿主观察状态暂时不可用。"],
  ["host_image_handoff_not_found", "未找到当前宿主图片交接。"],
  ["host_image_handoff_state_invalid", "当前宿主图片交接状态无效。"],
  ["host_image_import_failed", "导入宿主图片失败。"],
  ["host_image_output_invalid", "宿主返回的图片输出无效。"],
  ["host_image_request_invalid", "宿主图片交接参数无效。"],
  ["image_canvas_destroyed", "当前图片的画布已经销毁。"],
  ["image_task_failed", "图片任务执行失败。"],
  ["invalid_json", "图片运行时输入不是有效 JSON。"],
  ["invalid_task", "图片任务参数无效。"],
  ["mask_policy_missing", "当前标注缺少可验证的蒙版策略。"],
  ["mask_policy_unsupported", "当前标注使用旧版蒙版策略，请重新打开画布并提交。"],
  ["missing_edit_submission", "当前图片存在待发送画布提交，但缺少提交 ID。"],
  ["project_binding_conflict", "当前图片项目绑定已经关联到另一个项目。"],
  ["project_binding_invalid", "图片项目绑定 ID 无效。"],
  ["project_binding_required", "缺少有效的图片项目绑定。"],
  ["project_binding_state_invalid", "图片项目绑定状态无效。"],
  ["project_binding_unavailable", "图片项目绑定状态暂时不可用。"],
  ["project_root_invalid", "图片项目根目录无效。"],
  ["project_root_is_plugin_root", "插件安装目录不能作为图片项目根目录。"],
  ["stale_edit_submission", "画布提交已过期、已更新或已经使用。"],
  ["unsupported_capability", "当前图片模型不支持请求的能力。"],
  ["unsupported_model_profile", "当前图片模型配置不受支持。"],
  ["image_config_changed", "图片配置在项目绑定后发生变化，请重新显式绑定当前图片项目。"],
  ["image_config_invalid", "用户图片配置文件无效或不可安全读取。"],
  ["image_config_missing", "用户图片配置缺失。请创建 ~/.codex/openai-compatible-imagegen/config.json。"],
  ["image_config_exists", "用户图片配置已经存在，初始化不会覆盖现有文件。"],
  ["image_config_write_failed", "无法安全写入图片配置。"],
  ["image_config_update_invalid", "图片配置修改内容无效。"],
  ["image_config_update_forbidden", "图片配置修改包含不允许的字段。"],
  ["project_config_missing", "项目图片配置不存在，请先初始化或创建项目覆盖文件。"],
  ["output_directory_invalid", "输出目录必须是图片项目内的安全目录。"],
  ["project_config_forbidden", "项目图片配置包含不允许覆盖的字段。"],
  ["project_config_invalid", "项目图片配置文件无效或不可安全读取。"],
  ["image_job_not_found", "未找到当前图片任务，请核对项目和任务 ID。"],
  ["image_job_conflict", "提交键已用于其他图片请求。查询原任务；新生成意图请使用新的提交键。"],
  ["image_job_config_changed", "任务创建后的图片配置已变化，不能恢复执行。请先恢复原配置并重新绑定项目。"],
  ["image_job_state_invalid", "图片任务状态无效，未重新发送图片请求。"],
  ["image_job_state_unavailable", "图片任务状态暂时不可用，请使用原提交键或任务 ID 查询，勿创建重复请求。"],
  ["image_job_ownership_lost", "图片任务执行权已失效，请查询原任务状态。"],
  ["image_job_cancelled", "图片任务尚未发出的请求已取消；已发出的请求可能仍在处理。"],
  ["image_job_outcome_unknown", "图片请求的结果尚未确认，未自动重新生成。"],
];

export const stableToolErrorMessages = new Map(STABLE_TOOL_ERROR_ENTRIES);

export function isStableToolErrorCode(code) {
  return typeof code === "string" && stableToolErrorMessages.has(code);
}

export function stableToolErrorCodeFromText(text) {
  if (typeof text !== "string") return null;
  const match = /^([a-z][a-z0-9_]{0,63}):(?:\s|$)/.exec(text);
  const code = match?.[1] || null;
  return isStableToolErrorCode(code) ? code : null;
}
